import React from "react";
import { Download, Printer } from "lucide-react";
import type { AnalysisResult } from "../../types/analysis";
import { buildReportPdf, type PdfLine } from "../../utils/pdfReport";

interface ReportBarProps {
  result: AnalysisResult;
  fileName: string;
  fileSize: string;
  generatedAt: string | null;
}

const VERDICT_LABEL: Record<AnalysisResult["verdict"], string> = {
  LIKELY_AI_GENERATED: "Likely AI-generated",
  LIKELY_REAL: "Likely real photograph",
};

export const ReportBar: React.FC<ReportBarProps> = ({
  result,
  fileName,
  fileSize,
  generatedAt,
}) => {
  const handleDownload = () => {
    const pct = (v: number) => `${Math.round(v * 100)}%`;
    const lines: PdfLine[] = [
      { text: "SIGNALSCOPE - AI IMAGE FORENSICS REPORT", bold: true, size: 16 },
      {
        text: `Generated: ${
          generatedAt ? new Date(generatedAt).toLocaleString() : "-"
        }`,
        size: 9,
      },
      { text: `Source file: ${fileName}${fileSize ? ` (${fileSize})` : ""}`, size: 9 },

      { text: "VERDICT", bold: true, size: 12, gapBefore: true },
      {
        text: `${VERDICT_LABEL[result.verdict]}  -  confidence ${pct(
          result.confidence
        )}`,
        size: 10,
      },
    ];

    if (result.evidence?.explanation) {
      lines.push({ text: "WHY THIS VERDICT", bold: true, size: 12, gapBefore: true });
      lines.push({ text: result.evidence.explanation, size: 10 });
    }

    if (result.robustness) {
      lines.push({ text: "ROBUSTNESS", bold: true, size: 12, gapBefore: true });
      lines.push({
        text: `Original ${pct(result.robustness.original)}   JPEG ${pct(
          result.robustness.compressed
        )}   Resized ${pct(result.robustness.resized)}   Screenshot ${pct(
          result.robustness.screenshot
        )}`,
        size: 10,
      });
    }

    if (result.generalization?.auc != null) {
      lines.push({ text: "GENERALIZATION", bold: true, size: 12, gapBefore: true });
      lines.push({
        text: `AUC ${result.generalization.auc.toFixed(
          2
        )} / 1.00   Score ${pct(result.generalization.auc)}`,
        size: 10,
      });
    }

    lines.push({
      text: "Probabilistic output from an automated classifier. This is an investigative signal, not proof. Verify before acting.",
      size: 9,
      gapBefore: true,
    });
    lines.push({ text: "Generated by SignalScope", size: 9, gapBefore: true });

    const blob = buildReportPdf(lines);
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `signalscope-report-${Date.now()}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="no-print flex flex-col sm:flex-row items-stretch sm:items-center gap-3 border border-line bg-panel p-4">
      <p className="text-[11px] leading-relaxed text-dim sm:flex-1">
        Export the full finding as a PDF report.
      </p>
      <div className="flex gap-3">
        <button
          id="download-report-button"
          onClick={handleDownload}
          className="flex flex-1 sm:flex-none items-center justify-center gap-2 rounded-lg bg-neon text-void px-5 py-2.5 text-xs font-extrabold tracking-wider transition hover:brightness-110 active:scale-[0.99] focus:outline-none focus:ring-2 focus:ring-neon/60"
        >
          <Download size={15} />
          DOWNLOAD PDF
        </button>
        <button
          id="print-report-button"
          onClick={() => window.print()}
          className="flex flex-1 sm:flex-none items-center justify-center gap-2 rounded-lg border border-line2 bg-panel2 px-5 py-2.5 text-xs font-bold tracking-wider text-bright transition hover:bg-panel2/70 active:scale-[0.99] focus:outline-none focus:ring-2 focus:ring-neon/40"
        >
          <Printer size={15} />
          PRINT
        </button>
      </div>
    </div>
  );
};
